### ISSUE TITLE
Mint manga что то сломалось 

### ISSUE THREAD

**Issue by Zack95** [AcidBear/mngDownloader#7]
Качаю вот эту манку  http://mintmanga.com/prison_school
Вот скриншот 
![2017-09-08 11 28 31](https://user-images.githubusercontent.com/22136377/30202970-00471d3a-9489-11e7-8f36-1d80587a78a8.png)

И текстовый вывод 
\`
        MacBook-Pro-Zack95:mngDownloader-master ilya$ cd                      /Users/ilya/Documents/Program/Python/mngDownloader-master
        MacBook-Pro-Zack95:mngDownloader-master ilya$ python3 console.py 

    Введите название манги. Или нажмите Ctrl+C для выхода.
    Если хотите ввести прямую ссылку на мангу, введите '--full-link'
    Школа-Тюрьма

    Как фильтровать додзинси? (0-без додзинси, 1-только додзинси, 2-без разницы)
    2

    1. Prison School Школа-Тюрьма

    Выберите название манги из списка. (1-1)
    1

    Последние 5 глав:

	vol.27/ch.262 Школа-Тюрьма 27 - 262 Три идиота новое
	vol.26/ch.261 Школа-Тюрьма 26 - 261 Похитители велосипедов
	vol.26/ch.260 Школа-Тюрьма 26 - 260 Аэропорт
	vol.26/ch.259 Школа-Тюрьма 26 - 259 Великолепная суббота
	vol.26/ch.258 Школа-Тюрьма 26 - 258 Ты не ты

    Введите номера глав, которые вы хотите скачать, через пробел.
    Если хотите скачать все главы, нажмите ENTER.
    Если хотите посмотреть весь список глав, введите '--all'.

    Traceback (most recent call last):
      File "console.py", line 291, in <module>
        chapter['number'])
      File "/Users/ilya/Documents/Program/Python/mngDownloader-   master/modules/downloader/manga.py", line 138, in setChapterToDownload
        chapter['number'])
      File "/Users/ilya/Documents/Program/Python/mngDownloader-  master/modules/downloader/chapters.py", line 16, in __init__
        self.page = helpers.downloadPage(self.link)
      File "/Users/ilya/Documents/Program/Python/mngDownloader-master/modules/downloader/helpers.py", line 16, in downloadPage
        doc = lxml.html.parse(link)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lxml/html/__init__.py", line 789, in parse
        return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
      File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
      File "parser.pxi", line 1791, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:105979)
      File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106278)
      File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:105277)
      File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:100227)
      File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc  (src/lxml/lxml.etree.c:94350)
      File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
      File "parser.pxi", line 618, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94818)
    OSError: Error reading file 'http://mintmanga.com/prison_school/vol18/178?mature=1': failed to load  HTTP resource
    MacBook-Pro-Zack95:mngDownloader-master ilya$
 \`

**Comment by Zack95** [comment]
if 
MacBook-Pro-Zack95:parser ilya$ python3 parser.py readmanga
Traceback (most recent call last):
  File "parser.py", line 4, in <module>
    from parse_mangareader import parse as mreader_parse
ImportError: No module named 'parse_mangareader'
MacBook-Pro-Zack95:parser ilya$

**Comment by AcidBear** [comment]
После попытки повторить твои дейстия у меня сломалась МинтМанга, хех. 

Так или иначе, чинить ничего не буду, т.к. на маленькой манге всё работает.
Единственное. что я могу посоветовать - качать большую мангу частями.

**Comment by AcidBear** [comment]
Добавил задержки при загрузки манги и информации о ней. Грузится теперь всё будет дольше, но это должно помочь при загрузке большой манги за раз (в теории).

**Comment by AcidBear** [comment]
Добавил немного задержек при загрузки манги и информации о ней. Но это должно помочь в загрузке большой манги за раз (в теории).

**Comment by Zack95** [comment]
Можешь откатить на версию без задержек ? 
Новая работает вот так 
![2017-09-15 11 50 40](https://user-images.githubusercontent.com/22136377/30474395-3bc0bdac-9a0c-11e7-8940-8f1c7c42cbea.png)

**Comment by AcidBear** [comment]
Ну, я даже не знаю. У меня всё работает.

![21312](https://user-images.githubusercontent.com/10726780/30519261-78a40dfe-9ba2-11e7-8a28-e9bdf21581ac.png)

Могу посоветовать пройтись дебаггером, чтобы понять на каком месте программа крашится.
`python3 -m pdb console.py`
И нажимать `next` до момента краша. И потом запостить лог.

Ну, или в крайнем случае использовать более раннюю версию. [Например.](https://github.com/AcidBear/mngDownloader/tree/bb670b8def993ea1c7f689ec38dfd9ba8abfa98b)

**Comment by AcidBear** [comment]
> ReadMangaDownloader
[Серьёзно?](https://github.com/squizduos/ReadMangaDownloader)
